// lib/mock-data.ts
//
// Placeholder data shaped exactly like rows from `biochar_companies` after
// Stage 1 (agent1_extractor.py) and Stage 2 (agent2_verifier.py) have run.
// Swap `mockCompanies` / `mockNews` for real fetches against the Postgres
// REST gateway once it's available (see Project_Workflow_Architecture_Hybrid.md, Stage 5).

import { BiocharCompany, NewsItem } from "./types";

export const mockCompanies: BiocharCompany[] = [
  {
    id: 1,
    company_name: "Black Bull Biochar",
    product_service: "Premium lump biochar for horticulture and soil remediation",
    benefit_usp: "Kiln-fired in small batches for consistent porosity",
    web_youtube_link: "https://blackbullbiochar.com",
    opportunities: "Bulk supply contracts with regional garden centres",
    geographical_coverage: "North Yorkshire, UK",
    contact: "sales@blackbullbiochar.com",
    source: "PDF Guide",
    verification_status: "VERIFIED",
    companies_house_number: "13245678",
    companies_house_status: "active",
    verification_notes: "Exact match to 'BLACK BULL BIOCHAR LTD' (#13245678). Status: active.",
    ai_confidence: "HIGH",
    ai_reasoning: "Black Bull Biochar Ltd is an exact match for Black Bull Biochar.",
    verified_at: "2026-07-18T09:14:00Z",
  },
  {
    id: 2,
    company_name: "Carbogenics",
    product_service: "CreChar activated biochar filtration media",
    benefit_usp: "Repurposes distillery draff into high-value carbon products",
    web_youtube_link: "https://www.carbogenics.com",
    opportunities: "Partnerships with water treatment providers",
    geographical_coverage: "Scotland, UK",
    contact: "hello@carbogenics.com",
    source: "https://www.carbogenics.com",
    verification_status: "VERIFIED",
    companies_house_number: "SC582910",
    companies_house_status: "active",
    verification_notes: "Exact match to 'CARBOGENICS LIMITED' (#SC582910). Status: active.",
    ai_confidence: "HIGH",
    ai_reasoning: "Exact name match after normalizing: 'Carbogenics' = 'Carbogenics Limited'.",
    verified_at: "2026-07-19T11:02:00Z",
  },
  {
    id: 3,
    company_name: "Earthly Biochar",
    product_service: "Bagged soil-enhancing biochar for home growers",
    benefit_usp: "Locally sourced feedstock, low food-mile carbon footprint",
    web_youtube_link: "https://earthlybiochar.com/pages/about-us",
    opportunities: "Retail listings with national garden chains",
    geographical_coverage: "South West England",
    contact: "info@earthlybiochar.com",
    source: "https://earthlybiochar.com/pages/about-us",
    verification_status: "UNREGISTERED",
    companies_house_number: null,
    companies_house_status: null,
    verification_notes:
      "No results found in Companies House. Likely a sole trader or unincorporated business.",
    ai_confidence: "HIGH",
    ai_reasoning: "No search results returned from Companies House register.",
    verified_at: "2026-07-17T15:40:00Z",
  },
  {
    id: 4,
    company_name: "Argoed Coppice",
    product_service: "Woodland-managed lump charcoal and biochar",
    benefit_usp: "FSC-certified coppicing supports local biodiversity",
    web_youtube_link: "https://www.argoedcoppice.co.uk",
    opportunities: "Expansion into pyrolysis equipment demonstrations",
    geographical_coverage: "Powys, Wales",
    contact: "01597 000000",
    source: "PDF Guide",
    verification_status: "UNREGISTERED",
    companies_house_number: null,
    companies_house_status: null,
    verification_notes:
      "AI reviewed 2 candidates, no genuine match. Likely sole trader. Data issues: No web link provided.",
    ai_confidence: "HIGH",
    ai_reasoning:
      "Automotive and Business Services are completely different industries from a forestry/coppice business.",
    verified_at: "2026-07-16T08:21:00Z",
  },
  {
    id: 5,
    company_name: "Severn Pyrolysis Systems",
    product_service: "Modular pyrolysis kiln manufacturing",
    benefit_usp: "Turnkey on-farm units for agricultural residue processing",
    web_youtube_link: "https://severnpyrolysis.co.uk",
    opportunities: "Export enquiries from EU biochar cooperatives",
    geographical_coverage: "Gloucestershire, UK",
    contact: "enquiries@severnpyrolysis.co.uk",
    source: "https://severnpyrolysis.co.uk",
    verification_status: "DISSOLVED",
    companies_house_number: "09871234",
    companies_house_status: "dissolved",
    verification_notes: "Exact match to 'SEVERN PYROLYSIS SYSTEMS LTD' (#09871234). Status: dissolved.",
    ai_confidence: "HIGH",
    ai_reasoning: "Exact name match after normalizing: 'Severn Pyrolysis Systems' = 'Severn Pyrolysis Systems Ltd'.",
    verified_at: "2026-07-15T13:55:00Z",
  },
  {
    id: 6,
    company_name: "CapChar",
    product_service: "Industrial-scale biochar for construction composites",
    benefit_usp: "Biochar-infused concrete additive reduces embodied carbon",
    web_youtube_link: "https://www.capchar.co.uk",
    opportunities: "Trials with regional construction contractors",
    geographical_coverage: "West Midlands, UK",
    contact: "team@capchar.co.uk",
    source: "PDF Guide",
    verification_status: "VERIFIED",
    companies_house_number: "14009821",
    companies_house_status: "active",
    verification_notes: "Exact match to 'CAPCHAR LTD' (#14009821). Status: active.",
    ai_confidence: "HIGH",
    ai_reasoning: "Exact name match after normalizing: 'CapChar' = 'CAPCHAR LTD'.",
    verified_at: "2026-07-20T10:05:00Z",
  },
  {
    id: 7,
    company_name: "Carbon Farmers",
    product_service: "Agricultural consultancy for biochar soil amendment",
    benefit_usp: "Independent trials data on yield and carbon drawdown",
    web_youtube_link: "https://carbonfarmers.co.uk",
    opportunities: "Grant-funded pilot programmes with local councils",
    geographical_coverage: "East Anglia, UK",
    contact: "01223 000111",
    source: "PDF Guide",
    verification_status: "UNREGISTERED",
    companies_house_number: null,
    companies_house_status: null,
    verification_notes: "AI reviewed 2 candidates, no genuine match. Likely sole trader.",
    ai_confidence: "HIGH",
    ai_reasoning: "None of the candidates are 'Carbon Farmers'. Abbey Farmers is a different business.",
    verified_at: "2026-07-14T09:30:00Z",
  },
  {
    id: 8,
    company_name: "Highland Char Collective",
    product_service: "Community-scale biochar production and training",
    benefit_usp: "Not-for-profit model reinvests margin into reforestation",
    web_youtube_link: null,
    opportunities: "Seeking Companies House registration in progress",
    geographical_coverage: "Highlands, Scotland",
    contact: "info@highlandchar.scot",
    source: "https://highlandchar.scot",
    verification_status: "UNKNOWN_STATUS",
    companies_house_number: "SC601422",
    companies_house_status: "converted-closed",
    verification_notes: "AI matched to 'HIGHLAND CHAR COLLECTIVE CIC' (#SC601422). Status: converted-closed.",
    ai_confidence: "MEDIUM",
    ai_reasoning: "Name and sector both align, but the CIC record shows a non-standard status.",
    verified_at: "2026-07-13T16:12:00Z",
  },
  {
    id: 9,
    company_name: "Tyne Valley Biochar Works",
    product_service: "Contract pyrolysis processing for forestry waste",
    benefit_usp: "Mobile kiln units deployed directly to felling sites",
    web_youtube_link: "https://www.youtube.com/watch?v=tvbiocharworks",
    opportunities: "Long-term feedstock supply agreements with sawmills",
    geographical_coverage: "North East England",
    contact: "ops@tynevalleybiochar.co.uk",
    source: "PDF Guide",
    verification_status: "VERIFIED",
    companies_house_number: "11229384",
    companies_house_status: "active",
    verification_notes: "AI matched to 'TYNE VALLEY BIOCHAR WORKS LTD' (#11229384). Status: active.",
    ai_confidence: "HIGH",
    ai_reasoning: "Tyne Valley Biochar Works Ltd is an unambiguous match for Tyne Valley Biochar Works.",
    verified_at: "2026-07-21T12:47:00Z",
  },
  {
    id: 10,
    company_name: "Fenland Soil Carbon",
    product_service: "Peatland-alternative biochar soil conditioner",
    benefit_usp: "Targets fenland farms transitioning away from peat extraction",
    web_youtube_link: "https://fenlandsoilcarbon.com",
    opportunities: "DEFRA pilot scheme applications open",
    geographical_coverage: "Cambridgeshire, UK",
    contact: "contact@fenlandsoilcarbon.com",
    source: "https://fenlandsoilcarbon.com",
    verification_status: "API_ERROR",
    companies_house_number: null,
    companies_house_status: null,
    verification_notes: "Companies House API Error: HTTP 429",
    ai_confidence: null,
    ai_reasoning: null,
    verified_at: null,
  },
];

export const mockNews: NewsItem[] = [
  {
    id: "n1",
    publishedAt: "2026-07-21T07:00:00Z",
    bullets: [
      "UK biochar carbon credit certification body updates verification thresholds for 2026.",
      "Producers must now report feedstock provenance alongside pyrolysis batch records.",
      "Trade body estimates compliant supply will tighten before Q4 audits begin.",
    ],
    sourceName: "Resource Efficiency News",
    sourceUrl: "https://example.com/biochar-cert-update",
  },
  {
    id: "n2",
    publishedAt: "2026-07-20T07:00:00Z",
    bullets: [
      "DEFRA opens a second round of soil carbon pilot funding for fenland regions.",
      "Grants prioritise projects pairing biochar amendment with reduced tillage.",
      "Applications close at the end of September.",
    ],
    sourceName: "Farming Futures",
    sourceUrl: "https://example.com/defra-soil-carbon-round-two",
  },
  {
    id: "n3",
    publishedAt: "2026-07-18T07:00:00Z",
    bullets: [
      "Construction sector trials biochar-infused concrete additives at scale.",
      "Early results suggest embodied carbon reductions without strength loss.",
      "Several UK contractors plan wider adoption pending certification.",
    ],
    sourceName: "Built Environment Weekly",
    sourceUrl: "https://example.com/biochar-concrete-trials",
  },
  {
    id: "n4",
    publishedAt: "2026-07-16T07:00:00Z",
    bullets: [
      "Mobile pyrolysis units gain traction for forestry residue processing.",
      "On-site conversion cuts haulage costs for remote timber operations.",
      "Manufacturers report a growing order backlog into next year.",
    ],
    sourceName: "Forestry Journal UK",
    sourceUrl: "https://example.com/mobile-pyrolysis-units",
  },
  {
    id: "n5",
    publishedAt: "2026-07-14T07:00:00Z",
    bullets: [
      "Companies House flags a rise in dissolved entities across green-tech SIC codes.",
      "Analysts link the trend to tighter early-stage funding conditions.",
      "Buyers are advised to verify supplier registration before contracting.",
    ],
    sourceName: "Green Business Monitor",
    sourceUrl: "https://example.com/companies-house-greentech-trend",
  },
  {
    id: "n6",
    publishedAt: "2026-07-11T07:00:00Z",
    bullets: [
      "Distillery by-product conversion projects expand across Scotland.",
      "Draff-to-biochar pathways cut waste disposal costs for producers.",
      "Regional development funds earmark support for scale-up facilities.",
    ],
    sourceName: "Scotland Bioeconomy Report",
    sourceUrl: "https://example.com/distillery-byproduct-biochar",
  },
];
